// Mock 数据 — 完整覆盖文档 Section 7
// 注:日期相对今天动态生成,保证 Demo 时段网格有可约时段
import type {
  Announcement,
  Appointment,
  CoachProfile,
  CoachSlot,
  User,
  Venue,
  ViolationRecord,
} from './types';
import { formatDate, getNextNDays } from './utils';

// 动态日期偏移助手:今天+N天
function day(n: number): string {
  // getNextNDays(n) 返回长度为 n 的数组(索引 0..n-1),最后一个是今天+n
  return formatDate(getNextNDays(n + 1)[n]);
}
function isoDaysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function isoDaysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

// ========== 用户(10 人,含补充的管理员) ==========
export const mockUsers: User[] = [
  {
    id: 'u1',
    studentId: '22300110001',
    password: 'password123',
    name: '刘小明',
    department: '计算机科学学院',
    grade: '2023级',
    role: 'member',
    violationCount: 1,
    bannedUntil: null,
    createdAt: isoDaysAgo(120),
  },
  {
    id: 'u2',
    studentId: '22300150002',
    password: 'password123',
    name: '张明',
    department: '计算机科学学院',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(200),
  },
  {
    id: 'u3',
    studentId: '22300200003',
    password: 'password123',
    name: '李晓燕',
    department: '新闻学院',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(180),
  },
  {
    id: 'u4',
    studentId: '22300120004',
    password: 'password123',
    name: '王浩',
    department: '体育教学部',
    grade: '2021级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(300),
  },
  {
    id: 'u5',
    studentId: '22300300005',
    password: 'password123',
    name: '陈思怡',
    department: '外文学院',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(150),
  },
  {
    id: 'u6',
    studentId: '22300080006',
    password: 'password123',
    name: '赵宇航',
    department: '物理系',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(160),
  },
  {
    id: 'u7',
    studentId: '22300150007',
    password: 'password123',
    name: '周佳琪',
    department: '管理学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(100),
  },
  {
    id: 'u8',
    studentId: '22300100008',
    password: 'password123',
    name: '林浩然',
    department: '数学科学学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(90),
  },
  {
    id: 'u9',
    studentId: '22300060009',
    password: 'password123',
    name: '吴雨桐',
    department: '国际关系学院',
    grade: '2022级',
    role: 'member',
    violationCount: 3,
    bannedUntil: isoDaysFromNow(23), // 仍处禁约期
    createdAt: isoDaysAgo(140),
  },
  {
    id: 'u10',
    studentId: '00000000000',
    password: 'admin123',
    name: '平台管理员',
    department: '社团联合会',
    grade: '—',
    role: 'admin',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(365),
  },
];

// ========== 场馆(6 个) ==========
export const mockVenues: Venue[] = [
  {
    id: 'v1',
    name: '邯郸南区健身房',
    campus: 'handan-south',
    address: '邯郸校区南区学生活动中心B1',
    openTime: '08:00',
    closeTime: '22:00',
    capacity: 30,
    facilities: ['跑步机', '哑铃区', '拉伸区', '力量区'],
    description: '南区主力场馆,器械齐全,适合入门和进阶训练',
    bookable: true,
    displayOrder: 1,
  },
  {
    id: 'v2',
    name: '邯郸北区健身房',
    campus: 'handan-north',
    address: '邯郸校区北区体育馆2楼',
    openTime: '08:00',
    closeTime: '22:00',
    capacity: 25,
    facilities: ['有氧器械', '自由重量', '拉伸区', '体态矫正区'],
    description: '安静训练环境,适合基础力量和体态纠正',
    bookable: true,
    displayOrder: 2,
  },
  {
    id: 'v3',
    name: '五六教工会健身房',
    campus: 'wuliu',
    address: '第五六教学楼工会活动中心3楼',
    openTime: '10:00',
    closeTime: '21:00',
    capacity: 20,
    facilities: ['综合训练区', '跑步机', '哑铃区'],
    description: '紧凑型训练空间,适合进阶力量和自由重量训练',
    bookable: true,
    displayOrder: 3,
  },
  {
    id: 'v4',
    name: '江湾体育馆',
    campus: 'jiangwan',
    address: '江湾校区体育中心',
    openTime: '06:00',
    closeTime: '22:00',
    capacity: 200,
    facilities: ['有氧训练区', '力量训练区', '多功能操房', '游泳池', '休息区'],
    description: '江湾旗舰场馆,设施最齐全,暂未开放预约',
    bookable: false,
    displayOrder: 4,
    imageUrl: '/images/venue-flagship.jpg',
  },
  {
    id: 'v5',
    name: '枫林校区健身房',
    campus: 'fenglin',
    address: '枫林校区学生活动中心',
    openTime: '08:00',
    closeTime: '20:00',
    capacity: 15,
    facilities: ['基础器械'],
    description: '基础训练设施,暂未开放预约',
    bookable: false,
    displayOrder: 5,
  },
  {
    id: 'v6',
    name: '张江校区健身房',
    campus: 'zhangjiang',
    address: '张江校区体育设施',
    openTime: '08:00',
    closeTime: '20:00',
    capacity: 15,
    facilities: ['基础器械', '拉伸区'],
    description: '基础训练设施,暂未开放预约',
    bookable: false,
    displayOrder: 6,
  },
];

// ========== 教练(5 已认证 + 2 待审核) ==========
export const mockCoaches: CoachProfile[] = [
  {
    id: 'c1',
    userId: 'u2',
    name: '张明',
    department: '计算机科学学院',
    grade: '2022级',
    specialties: ['力量训练', '新手入门'],
    styleDesc: '耐心带零基础同学,注重动作规范和安全,不会让你尴尬',
    isBeginnerFriendly: true,
    isFemaleFriendly: false,
    totalSessions: 42,
    totalStudents: 28,
    certStatus: 'approved',
    venues: ['v1', 'v2'],
    createdAt: isoDaysAgo(200),
  },
  {
    id: 'c2',
    userId: 'u3',
    name: '李晓燕',
    department: '新闻学院',
    grade: '2023级',
    specialties: ['有氧减脂', '形体矫正'],
    styleDesc: '帮助同学建立正确训练习惯,特别是女生入门训练',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 28,
    totalStudents: 19,
    certStatus: 'approved',
    venues: ['v1', 'v2'],
    createdAt: isoDaysAgo(180),
  },
  {
    id: 'c3',
    userId: 'u4',
    name: '王浩',
    department: '体育教学部',
    grade: '2021级',
    specialties: ['力量训练', '增肌训练'],
    styleDesc: '3年训练经验,擅长力量入门和增肌计划制定',
    isBeginnerFriendly: false,
    isFemaleFriendly: false,
    totalSessions: 65,
    totalStudents: 41,
    certStatus: 'approved',
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(300),
  },
  {
    id: 'c4',
    userId: 'u5',
    name: '陈思怡',
    department: '外文学院',
    grade: '2023级',
    specialties: ['有氧', '拉伸放松'],
    styleDesc: '温柔耐心,适合零基础和想要放松训练的同学',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 15,
    totalStudents: 11,
    certStatus: 'approved',
    venues: ['v2'],
    createdAt: isoDaysAgo(150),
  },
  {
    id: 'c5',
    userId: 'u6',
    name: '赵宇航',
    department: '物理系',
    grade: '2022级',
    specialties: ['力量训练', '有氧'],
    styleDesc: '理科生思维,注重训练科学性和渐进式超负荷',
    isBeginnerFriendly: true,
    isFemaleFriendly: false,
    totalSessions: 38,
    totalStudents: 25,
    certStatus: 'approved',
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(160),
  },
  {
    id: 'c6',
    userId: 'u7',
    name: '孙婷婷',
    department: '管理学院',
    grade: '2023级',
    specialties: ['形体矫正', '拉伸放松'],
    styleDesc: '帮助女生建立正确训练习惯,注重形体和体态改善',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 0,
    totalStudents: 0,
    certStatus: 'pending',
    certAppliedAt: isoDaysAgo(2),
    venues: ['v2'],
    createdAt: isoDaysAgo(100),
  },
  {
    id: 'c7',
    userId: 'u8',
    name: '周文博',
    department: '数学科学学院',
    grade: '2021级',
    specialties: ['力量训练'],
    styleDesc: '4年训练经验,擅长力量入门和计划制定',
    isBeginnerFriendly: false,
    isFemaleFriendly: false,
    totalSessions: 0,
    totalStudents: 0,
    certStatus: 'pending',
    certAppliedAt: isoDaysAgo(1),
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(90),
  },
];

// ========== 教练可用时段(10 条,日期动态) ==========
// 保持文档的相对关系:s1/s2=今天+1, s3/s4=今天+2, s5=今天, s6=今天+2, s7=今天+3, s8=今天+1, s9=今天+3, s10=今天+3
export const mockSlots: CoachSlot[] = [
  { id: 's1', coachId: 'c1', venueId: 'v1', date: day(1), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's2', coachId: 'c1', venueId: 'v1', date: day(1), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's3', coachId: 'c2', venueId: 'v1', date: day(2), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's4', coachId: 'c2', venueId: 'v2', date: day(2), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's5', coachId: 'c3', venueId: 'v1', date: day(0), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's6', coachId: 'c3', venueId: 'v3', date: day(2), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's7', coachId: 'c4', venueId: 'v2', date: day(3), startTime: '08:00', endTime: '09:00', isAvailable: true },
  { id: 's8', coachId: 'c5', venueId: 'v1', date: day(1), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's9', coachId: 'c5', venueId: 'v3', date: day(3), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's10', coachId: 'c1', venueId: 'v2', date: day(3), startTime: '19:00', endTime: '20:00', isAvailable: true },
];

// ========== 预约记录(6 条,覆盖全部状态,日期动态) ==========
// a1 pending(本周,占 u1 额度), a2 approved(本周,占 u1 额度)
// a3 completed(上周,u7), a4 cancelled(上周,u1,记违约), a5 pending(本周,u8), a6 no_show(上上周,u9)
export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    studentId: 'u1',
    coachId: 'c1',
    venueId: 'v1',
    date: day(1),
    startTime: '14:00',
    endTime: '15:00',
    status: 'pending',
    trainingNote: '零基础,想学基本器械使用方法',
    createdAt: isoDaysAgo(0),
  },
  {
    id: 'a2',
    studentId: 'u1',
    coachId: 'c2',
    venueId: 'v2',
    date: day(2),
    startTime: '14:00',
    endTime: '15:00',
    status: 'approved',
    trainingNote: '想减脂,有氧训练为主',
    createdAt: isoDaysAgo(2),
  },
  {
    id: 'a3',
    studentId: 'u7',
    coachId: 'c3',
    venueId: 'v1',
    date: isoDaysAgo(7).slice(0, 10),
    startTime: '16:00',
    endTime: '17:00',
    status: 'completed',
    trainingNote: '力量训练入门',
    createdAt: isoDaysAgo(9),
  },
  {
    id: 'a4',
    studentId: 'u1',
    coachId: 'c5',
    venueId: 'v3',
    date: isoDaysAgo(5).slice(0, 10),
    startTime: '14:00',
    endTime: '15:00',
    status: 'cancelled',
    cancelReason: '教练未及时审核,系统自动取消',
    cancelledBy: 'system',
    cancelledAt: isoDaysAgo(4),
    createdAt: isoDaysAgo(6),
  },
  {
    id: 'a5',
    studentId: 'u8',
    coachId: 'c1',
    venueId: 'v1',
    date: day(2),
    startTime: '10:00',
    endTime: '11:00',
    status: 'pending',
    trainingNote: '想学卧推和深蹲',
    createdAt: isoDaysAgo(1),
  },
  {
    id: 'a6',
    studentId: 'u9',
    coachId: 'c4',
    venueId: 'v2',
    date: isoDaysAgo(10).slice(0, 10),
    startTime: '08:00',
    endTime: '09:00',
    status: 'no_show',
    trainingNote: '',
    createdAt: isoDaysAgo(12),
  },
];

// ========== 公告(3 条) ==========
export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann1',
    title: '【重要】2025年秋季学期带练预约已开放',
    content:
      '本学期邯郸南区、北区、五六教工会三场馆带练预约现已开放。欢迎新老社员预约,每周每人最多预约3次。请仔细阅读预约规则后再提交。',
    isPinned: true,
    status: 'published',
    publishedAt: isoDaysAgo(3),
  },
  {
    id: 'ann2',
    title: '暑期南区场馆开放时间调整通知',
    content: '7月1日至8月31日,邯郸南区健身房开放时间调整为08:00-20:00,请合理安排训练时间。',
    isPinned: false,
    status: 'published',
    publishedAt: isoDaysAgo(6),
  },
  {
    id: 'ann3',
    title: '新增3位认证教练,欢迎预约',
    content: '恭喜赵宇航、孙婷婷、周文博三位社员通过教练认证审核,现已开放预约时段。',
    isPinned: false,
    status: 'published',
    publishedAt: isoDaysAgo(9),
  },
];

// ========== 违约记录(2 条) ==========
export const mockViolations: ViolationRecord[] = [
  {
    id: 'vr1',
    userId: 'u9',
    appointmentId: 'a6',
    violationType: 'no_show',
    description: '2025-06-25 预约未到场(教练:陈思怡,邯郸北区 08:00-09:00)',
    createdAt: isoDaysAgo(10),
  },
  {
    id: 'vr2',
    userId: 'u1',
    appointmentId: 'a4',
    violationType: 'late_cancel',
    description: '2025-06-28 预约在开课前 12 小时内取消(教练:赵宇航,五六教工会 14:00-15:00)',
    createdAt: isoDaysAgo(5),
  },
];

// ========== 一键登录账号清单(登录页展示) ==========
export const QUICK_LOGIN_ACCOUNTS = [
  { studentId: '22300110001', password: 'password123', label: '学员·刘小明', desc: '普通社员,已预约2次' },
  { studentId: '22300150002', password: 'password123', label: '教练·张明', desc: '认证教练,有1条待审核' },
  { studentId: '22300060009', password: 'password123', label: '学员·吴雨桐', desc: '被禁约(测试禁约提示)' },
  { studentId: '00000000000', password: 'admin123', label: '管理员', desc: '后台全部权限' },
];
