// Mock 数据 — 完整覆盖文档 Section 7
// 注:日期相对今天动态生成,保证 Demo 时段网格有可约时段
import type {
  Announcement,
  Appointment,
  CoachProfile,
  CoachSlot,
  User,
  Venue,
  ViolationRecord,
} from './types';
import { formatDate, getNextNDays } from './utils';

// 动态日期偏移助手:今天+N天
function day(n: number): string {
  // getNextNDays(n) 返回长度为 n 的数组(索引 0..n-1),最后一个是今天+n
  return formatDate(getNextNDays(n + 1)[n]);
}
function isoDaysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function isoDaysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

// ========== 用户(20 人,含补充的管理员) ==========
export const mockUsers: User[] = [
  {
    id: 'u1',
    studentId: '22300110001',
    password: 'password123',
    name: '刘小明',
    department: '计算机科学学院',
    grade: '2023级',
    role: 'member',
    violationCount: 1,
    bannedUntil: null,
    createdAt: isoDaysAgo(120),
  },
  {
    id: 'u2',
    studentId: '22300150002',
    password: 'password123',
    name: '张明',
    department: '计算机科学学院',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(200),
  },
  {
    id: 'u3',
    studentId: '22300200003',
    password: 'password123',
    name: '李晓燕',
    department: '新闻学院',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(180),
  },
  {
    id: 'u4',
    studentId: '22300120004',
    password: 'password123',
    name: '王浩',
    department: '体育教学部',
    grade: '2021级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(300),
  },
  {
    id: 'u5',
    studentId: '22300300005',
    password: 'password123',
    name: '陈思怡',
    department: '外文学院',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(150),
  },
  {
    id: 'u6',
    studentId: '22300080006',
    password: 'password123',
    name: '赵宇航',
    department: '物理系',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(160),
  },
  {
    id: 'u7',
    studentId: '22300150007',
    password: 'password123',
    name: '周佳琪',
    department: '管理学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(100),
  },
  {
    id: 'u8',
    studentId: '22300100008',
    password: 'password123',
    name: '林浩然',
    department: '数学科学学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(90),
  },
  {
    id: 'u9',
    studentId: '22300060009',
    password: 'password123',
    name: '吴雨桐',
    department: '国际关系学院',
    grade: '2022级',
    role: 'member',
    violationCount: 3,
    bannedUntil: isoDaysFromNow(23), // 仍处禁约期
    createdAt: isoDaysAgo(140),
  },
  {
    id: 'u10',
    studentId: '00000000000',
    password: 'admin123',
    name: '平台管理员',
    department: '社团联合会',
    grade: '—',
    role: 'admin',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(365),
  },
  {
    id: 'u11',
    studentId: '22300180011',
    password: 'password123',
    name: '黄丽雯',
    department: '经济学院',
    grade: '2022级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(180),
  },
  {
    id: 'u12',
    studentId: '22300220012',
    password: 'password123',
    name: '何志强',
    department: '国际关系学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(120),
  },
  {
    id: 'u13',
    studentId: '22300050013',
    password: 'password123',
    name: '孙雨萱',
    department: '哲学学院',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(200),
  },
  {
    id: 'u14',
    studentId: '22300170014',
    password: 'password123',
    name: '林晨宇',
    department: '化学系',
    grade: '2021级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(280),
  },
  {
    id: 'u15',
    studentId: '22300250015',
    password: 'password123',
    name: '许佳音',
    department: '法学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(100),
  },
  {
    id: 'u16',
    studentId: '22300130016',
    password: 'password123',
    name: '郑浩宇',
    department: '环境科学与工程系',
    grade: '2022级',
    role: 'member',
    violationCount: 1,
    bannedUntil: null,
    createdAt: isoDaysAgo(160),
  },
  {
    id: 'u17',
    studentId: '22300280017',
    password: 'password123',
    name: '钱梦瑶',
    department: '中文系',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(140),
  },
  {
    id: 'u18',
    studentId: '22300090018',
    password: 'password123',
    name: '梁文博',
    department: '生命科学学院',
    grade: '2021级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(220),
  },
  {
    id: 'u19',
    studentId: '22300210019',
    password: 'password123',
    name: '陈雅婷',
    department: '社会发展与公共政策学院',
    grade: '2022级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(170),
  },
  {
    id: 'u20',
    studentId: '22300320020',
    password: 'password123',
    name: '李明轩',
    department: '历史系',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(90),
  },
  {
    id: 'u21',
    studentId: '22300330021',
    password: 'password123',
    name: '王芷若',
    department: '基础医学院',
    grade: '2022级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(110),
  },
  {
    id: 'u22',
    studentId: '22300340022',
    password: 'password123',
    name: '张远航',
    department: '微电子学院',
    grade: '2021级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(250),
  },
  {
    id: 'u23',
    studentId: '22300350023',
    password: 'password123',
    name: '刘思琪',
    department: '护理学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(80),
  },
  {
    id: 'u24',
    studentId: '22300360024',
    password: 'password123',
    name: '陈浩然',
    department: '航空航天系',
    grade: '2022级',
    role: 'member',
    violationCount: 1,
    bannedUntil: null,
    createdAt: isoDaysAgo(130),
  },
  {
    id: 'u25',
    studentId: '22300370025',
    password: 'password123',
    name: '赵诗涵',
    department: '高分子科学系',
    grade: '2023级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(170),
  },
  {
    id: 'u26',
    studentId: '22300380026',
    password: 'password123',
    name: '孙俊杰',
    department: '材料科学系',
    grade: '2021级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(210),
  },
  {
    id: 'u27',
    studentId: '22300390027',
    password: 'password123',
    name: '周雨薇',
    department: '公共卫生学院',
    grade: '2022级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(95),
  },
  {
    id: 'u28',
    studentId: '22300400028',
    password: 'password123',
    name: '吴子豪',
    department: '软件学院',
    grade: '2023级',
    role: 'member',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(70),
  },
  {
    id: 'u29',
    studentId: '22300410029',
    password: 'password123',
    name: '郑雅琳',
    department: '旅游学系',
    grade: '2022级',
    role: 'coach',
    violationCount: 0,
    bannedUntil: null,
    createdAt: isoDaysAgo(190),
  },
];

// ========== 场馆(6 个) ==========
export const mockVenues: Venue[] = [
  {
    id: 'v1',
    name: '邯郸南区健身房',
    campus: 'handan-south',
    address: '南区综合楼，游泳馆南侧',
    contactPhone: '55664996',
    openTime: '08:00',
    closeTime: '22:00',
    capacity: 30,
    facilities: ['跑步机8台', '椭圆机4台', '动感单车6台', '哑铃区(2.5-30kg)', '杠铃区', '龙门架', '高位下拉', '坐姿推举', '腿部推蹬', '卷腹机', '拉伸区'],
    description: '南区主力场馆,器械种类最齐全。配备完整的力量训练器械和有氧设备,是入门和进阶训练的首选场地。场地宽敞明亮,通风良好。',
    bookable: true,
    displayOrder: 1,
    features: ['空调全天开放', '饮用水供应', '储物柜', '新手友好时段'],
    layoutInfo: '南区综合楼内,游泳馆南侧。入口处为有氧区(跑步机+椭圆机),中部为力量区(哑铃架+组合器械),深处为自由重量区(深蹲架+卧推架)。',
    peakHours: '工作日17:00-19:30、周末14:00-17:00为高峰期,建议错峰训练',
    tips: ['周末下午人较多，建议提前预约', '储物柜需自带挂锁或使用电子锁', '更衣室位于入口右侧'],
    transportation: '从南区学生活动中心正门进入，游泳馆南侧即为健身房入口',
    rules: ['需携带校园卡刷卡进入', '必须穿着运动鞋(禁止拖鞋、皮鞋)', '训练结束后请归位器材', '禁止赤膊训练'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/r80U1wju77',
  },
  {
    id: 'v2',
    name: '邯郸北区健身房',
    campus: 'handan-north',
    address: '北区学生公寓98号楼南侧',
    contactPhone: '65642128',
    openTime: '08:00',
    closeTime: '22:00',
    capacity: 25,
    facilities: ['跑步机6台', '动感单车4台', '自由重量区', '深蹲架', '卧推架', '硬拉台', '哑铃区(2-25kg)', '功能性训练区', '瑜伽垫区', '泡沫轴', '体态矫正器械'],
    description: '北区体育馆配套健身房,训练环境安静舒适,特别适合力量训练和体态矫正。毗邻羽毛球馆,可预约联合训练。',
    bookable: true,
    displayOrder: 2,
    features: ['空调全天开放', '独立更衣室', '淋浴设施', '女生专属时段(每周三19:00-21:00)'],
    layoutInfo: '北区体育馆一楼西侧,约180㎡空间。前半区为力量训练区,后半区为有氧区和功能性训练区。独立更衣淋浴间在场馆外侧。',
    peakHours: '工作日18:00-20:00为高峰,周末相对空闲',
    tips: ['女生专属时段仅限女生教练带练或女生学员使用', '北区体育馆整体较新,设施维护良好', '可借用羽毛球馆做热身拉伸'],
    transportation: '北区学生公寓98号楼南侧,北区体育馆内',
    rules: ['需携带校园卡', '淋浴设施需自备毛巾和洗漱用品', '大重量训练建议结伴进行', '禁止在力量区内奔跑追逐'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/r80U1wju77',
  },
  {
    id: 'v3',
    name: '五六教工会健身房',
    campus: 'wuliu',
    address: '第五六教学楼工会活动中心3楼',
    contactPhone: '55664996',
    openTime: '10:00',
    closeTime: '21:00',
    capacity: 20,
    facilities: ['综合训练器2台', '跑步机4台', '哑铃区(5-35kg)', '杠铃', '深蹲架', '卧推凳', '引体向上架', '腹肌训练器', '拉伸带', '瑜伽球'],
    description: '位于教学区中心,地理位置便利。紧凑型训练空间,适合进阶力量训练和自由重量爱好者。训练氛围浓厚,常有高水平训练者交流。',
    bookable: true,
    displayOrder: 3,
    features: ['空调开放', '就近教学区', '训练交流氛围浓厚'],
    layoutInfo: '五六教工会3楼,约150㎡紧凑空间。进门右侧为有氧区,左侧和中部为力量区。空间较小但设施密度高。',
    peakHours: '午休时段12:00-13:30、课后17:30-19:00较为拥挤',
    tips: ['午休时段适合快节奏训练(45min内完成)', '空间紧凑,大重量动作注意周围同学安全', '这里有很多"隐藏高手",可以多交流学习'],
    transportation: '从五六教学楼之间的连廊上到3楼,工会活动中心门口有指示牌',
    rules: ['10:00才开放,不要早到', '空间有限,请勿占用过道', '器材使用完毕请立即归位', '保持安静,尊重其他训练者'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/r80U1wju77',
  },
  {
    id: 'v4',
    name: '江湾体育馆健身房',
    campus: 'jiangwan',
    address: '江湾校区综合体育馆内',
    contactPhone: '31242035',
    openTime: '06:00',
    closeTime: '22:00',
    capacity: 200,
    facilities: ['有氧训练区(跑步机12台、椭圆机6台、动感单车10台)', '力量训练区(全套自由重量、组合器械)', '多功能操房', '瑜伽室', '游泳池(25m标准池)', '休息区', '桑拿房'],
    description: '江湾校区旗舰场馆,总面积28800平方米。设施最齐全、规模最大的综合性体育馆,包含健身房、乒乓球室、体操多功能房、羽毛球场、网球场、篮球场、排球场、游泳馆等。',
    bookable: true,
    displayOrder: 4,
    features: ['旗舰级设施', '标准游泳池', '桑拿房', '超大空间'],
    layoutInfo: '综合体育馆一层为健身房和游泳池,二层及以上为各类球馆。健身房区域约500㎡,分区明确:有氧区→固定器械区→自由重量区→功能性训练区。',
    peakHours: '傍晚17:00-21:00人流量最大',
    tips: ['江湾校区设施最全但距离本部较远', '游泳池需要额外预约或购票', '桑拿房男女分开,需自带泳衣', '健身房无需预约但比较紧俏,下午4点后跑步机较紧张'],
    transportation: '从江湾校区东门或南门均可到达体育馆,校内摆渡车可达',
    rules: ['部分设施可能需要额外收费或预约', '游泳池必须佩戴泳帽', '请爱护旗舰设施,文明使用'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/75p31wju77',
  },
  {
    id: 'v5',
    name: '枫林综合体育馆健身房',
    campus: 'fenglin',
    address: '综合体育馆负一层',
    contactPhone: '54237917',
    openTime: '08:00',
    closeTime: '20:00',
    capacity: 15,
    facilities: ['跑步机3台', '动感单车2台', '综合训练器1台', '哑铃区(2-15kg)', '瑜伽垫', '拉伸区'],
    description: '枫林校区综合体育馆配套健身房,位于体育馆负一层。主要服务医学相关院系学生,设施虽不齐全但日常训练足够。',
    bookable: false,
    displayOrder: 5,
    features: ['基础训练', '就近宿舍', '无需预约'],
    layoutInfo: '综合体育馆负一层,约80㎡小型健身空间。与游泳馆、室内篮球场同层。',
    peakHours: '课余时间偶有人使用',
    tips: ['医学部同学课业繁忙,利用碎片时间锻炼很重要', '基础器械足够维持日常体能', '无需预约,持一卡通即可入场'],
    transportation: '综合体育馆负一层,从体育馆电梯直达',
    rules: ['设施较少,请按秩序使用', '关闭时间较早(20:00),请注意时间', '持校园卡入场'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/EwC11wju77',
  },
  {
    id: 'v6',
    name: '张江校区健身房',
    campus: 'zhangjiang',
    address: '学生活动中心三楼（食堂三楼）',
    contactPhone: '51355708',
    openTime: '08:00',
    closeTime: '20:00',
    capacity: 15,
    facilities: ['跑步机4台', '椭圆机2台', '综合训练器1台', '哑铃区(2-20kg)', '瑜伽垫', '拉伸区', '功能性训练器材'],
    description: '张江校区学生活动中心配套健身房,位于食堂三楼。服务信息科学相关院系学生,配备基础有氧和力量训练器材。',
    bookable: false,
    displayOrder: 6,
    features: ['基础训练', '科技氛围', '无需预约'],
    layoutInfo: '学生活动中心三楼(食堂三楼),约90㎡空间。与食堂同楼,训练后可直接就餐。',
    peakHours: '晚间使用率较高',
    tips: ['理工科同学久坐电脑前,更要重视肩颈腰背的放松训练', '训练后可直接到楼下食堂就餐,非常方便', '无需预约,持校园卡入场'],
    transportation: '学生活动中心三楼(食堂三楼),从食堂入口上楼梯或乘电梯均可到达',
    rules: ['设施有限,请合理分配使用时间', '编程久了来拉伸一下很舒服', '持校园卡入场'],
    mapImageUrl: 'https://aka.doubaocdn.com/s/6J8U1wju77',
  },
];

// ========== 教练(8 已认证 + 2 待审核) ==========
export const mockCoaches: CoachProfile[] = [
  {
    id: 'c1',
    userId: 'u2',
    name: '张明',
    department: '计算机科学学院',
    grade: '2022级',
    specialties: ['力量训练', '新手入门'],
    styleDesc: '耐心带零基础同学,注重动作规范和安全,不会让你尴尬',
    isBeginnerFriendly: true,
    isFemaleFriendly: false,
    totalSessions: 42,
    totalStudents: 28,
    certStatus: 'approved',
    venues: ['v1', 'v2'],
    createdAt: isoDaysAgo(200),
    trainingPhilosophy: '动作规范永远优先于重量。宁可轻一点,也要做对。学会了正确姿势,进步自然来。',
    rating: 4.8,
    studentReviews: [
      { id: 'r1', studentName: '同学A', rating: 5, content: '零基础入门,张明教练非常耐心,每个动作都反复纠正,完全不尴尬', date: isoDaysAgo(30) },
      { id: 'r2', studentName: '同学B', rating: 5, content: '从完全不会深蹲到能标准蹲60kg,两个月进步很明显', date: isoDaysAgo(15) },
      { id: 'r3', studentName: '同学C', rating: 4, content: '动作讲解很细致,不过有时候会讲太久哈哈', date: isoDaysAgo(7) },
    ],
    successCases: ['帮零基础同学2个月内掌握深蹲/卧推/硬拉三大项标准动作', '带练3位同学完成首次引体向上突破'],
  },
  {
    id: 'c2',
    userId: 'u3',
    name: '李晓燕',
    department: '新闻学院',
    grade: '2023级',
    specialties: ['有氧减脂', '形体矫正'],
    styleDesc: '帮助同学建立正确训练习惯,特别是女生入门训练',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 28,
    totalStudents: 19,
    certStatus: 'approved',
    venues: ['v1', 'v2'],
    createdAt: isoDaysAgo(180),
    trainingPhilosophy: '减脂不是挨饿,而是找到适合自己的运动节奏。享受运动的过程,结果自然会出现。',
    rating: 4.9,
    studentReviews: [
      { id: 'r4', studentName: '同学D', rating: 5, content: '作为女生第一次去健身房,晓燕姐让我完全没有压力,超推荐!', date: isoDaysAgo(20) },
      { id: 'r5', studentName: '同学E', rating: 5, content: '跟着练了一个月,体能提升很多,而且真的不枯燥', date: isoDaysAgo(10) },
    ],
    successCases: ['帮3位女生同学建立每周3练的习惯', '一位同学3个月体脂率从28%降到23%'],
  },
  {
    id: 'c3',
    userId: 'u4',
    name: '王浩',
    department: '体育教学部',
    grade: '2021级',
    specialties: ['力量训练', '增肌训练'],
    styleDesc: '3年训练经验,擅长力量入门和增肌计划制定',
    isBeginnerFriendly: false,
    isFemaleFriendly: false,
    totalSessions: 65,
    totalStudents: 41,
    certStatus: 'approved',
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(300),
    trainingPhilosophy: '渐进式超负荷是增肌的核心。记录每次训练数据,每周比上周多做一点,变化就在累积中。',
    rating: 4.7,
    studentReviews: [
      { id: 'r6', studentName: '同学F', rating: 5, content: '王浩教练很专业,训练计划制定得很科学,进步肉眼可见', date: isoDaysAgo(25) },
      { id: 'r7', studentName: '同学G', rating: 4, content: '训练强度不小,但效果确实好,适合有一定基础的同学', date: isoDaysAgo(12) },
    ],
    successCases: ['帮同学6个月增肌8kg且体脂保持不变', '指导多位同学突破卧推100kg大关'],
  },
  {
    id: 'c4',
    userId: 'u5',
    name: '陈思怡',
    department: '外文学院',
    grade: '2023级',
    specialties: ['有氧', '拉伸放松'],
    styleDesc: '温柔耐心,适合零基础和想要放松训练的同学',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 15,
    totalStudents: 11,
    certStatus: 'approved',
    venues: ['v2'],
    createdAt: isoDaysAgo(150),
    trainingPhilosophy: '训练不是苦行僧式的坚持,而是和自己身体的对话。放松也是一种训练。',
    rating: 5.0,
    studentReviews: [
      { id: 'r8', studentName: '同学H', rating: 5, content: '思怡姐的拉伸课太舒服了,做完感觉整个人都放松了', date: isoDaysAgo(18) },
      { id: 'r9', studentName: '同学I', rating: 5, content: '超级温柔的教练,很会照顾新手的感受', date: isoDaysAgo(5) },
    ],
    successCases: ['帮助多位久坐同学缓解肩颈酸痛', '引导5位零基础女生爱上规律锻炼'],
  },
  {
    id: 'c5',
    userId: 'u6',
    name: '赵宇航',
    department: '物理系',
    grade: '2022级',
    specialties: ['力量训练', '有氧'],
    styleDesc: '理科生思维,注重训练科学性和渐进式超负荷',
    isBeginnerFriendly: true,
    isFemaleFriendly: false,
    totalSessions: 38,
    totalStudents: 25,
    certStatus: 'approved',
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(160),
    trainingPhilosophy: '训练就像做实验,控制变量、记录数据、调整方案。用数据说话,少走弯路。',
    rating: 4.6,
    studentReviews: [
      { id: 'r10', studentName: '同学J', rating: 5, content: '教练会帮我记录每次训练数据,还能看到自己的进步曲线,很有成就感', date: isoDaysAgo(22) },
      { id: 'r11', studentName: '同学K', rating: 4, content: '很科学的训练方式,不过有时候讲公式有点多', date: isoDaysAgo(8) },
    ],
    successCases: ['帮同学制定科学训练计划,3个月卧推从40kg到70kg', '用数据分析帮多位同学突破训练平台期'],
  },
  {
    id: 'c6',
    userId: 'u13',
    name: '孙雨萱',
    department: '哲学学院',
    grade: '2022级',
    specialties: ['瑜伽', '冥想放松', '柔韧性训练'],
    styleDesc: '瑜伽爱好者,专注于身心平衡训练。擅长引导新手进入瑜伽世界,注重呼吸与动作的协调',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 22,
    totalStudents: 16,
    certStatus: 'approved',
    venues: ['v1', 'v2'],
    createdAt: isoDaysAgo(200),
    trainingPhilosophy: '瑜伽不是比谁更柔软,而是学会在呼吸之间找到身心平衡。每一个体式都是与自己对话的机会。',
    rating: 4.9,
    studentReviews: [
      { id: 'r12', studentName: '同学L', rating: 5, content: '第一次练瑜伽就被圈粉了,雨萱教练的引导特别温柔', date: isoDaysAgo(28) },
      { id: 'r13', studentName: '同学M', rating: 5, content: '考前焦虑的时候去上了一节冥想课,整个人都平静了', date: isoDaysAgo(14) },
    ],
    successCases: ['帮多位焦虑同学通过瑜伽冥想改善睡眠', '引导10位零基础同学掌握基础瑜伽体式'],
  },
  {
    id: 'c7',
    userId: 'u14',
    name: '林晨宇',
    department: '化学系',
    grade: '2021级',
    specialties: ['HIIT', '功能性训练', '爆发力训练'],
    styleDesc: '4年训练经验,注重功能性训练和运动表现提升。适合想要提升体能和运动能力的同学',
    isBeginnerFriendly: false,
    isFemaleFriendly: false,
    totalSessions: 52,
    totalStudents: 33,
    certStatus: 'approved',
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(280),
    trainingPhilosophy: '功能性训练让你不只是好看,更要好用。爆发力、协调性、耐力缺一不可。',
    rating: 4.5,
    studentReviews: [
      { id: 'r14', studentName: '同学N', rating: 5, content: '跟着林教练训练体能提升很大,现在打篮球都不累了', date: isoDaysAgo(35) },
      { id: 'r15', studentName: '同学O', rating: 4, content: '训练强度真的很大,但效果也很明显,适合想挑战自己的', date: isoDaysAgo(18) },
    ],
    successCases: ['帮校篮球队队员提升体能,赛季表现显著提高', '指导同学通过HIIT训练3个月减重8kg'],
  },
  {
    id: 'c8',
    userId: 'u17',
    name: '钱梦瑶',
    department: '中文系',
    grade: '2023级',
    specialties: ['普拉提', '核心训练', '体态矫正'],
    styleDesc: '温柔细致,专注于核心力量和体态改善。特别适合久坐的同学,帮助缓解腰背问题',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 18,
    totalStudents: 14,
    certStatus: 'approved',
    venues: ['v2'],
    createdAt: isoDaysAgo(140),
    trainingPhilosophy: '好体态是最好的气质。核心力量是身体的地基,地基稳了,什么都好建。',
    rating: 4.8,
    studentReviews: [
      { id: 'r16', studentName: '同学P', rating: 5, content: '久坐导致腰疼,跟着梦瑶练了一个月,腰真的好了很多!', date: isoDaysAgo(16) },
      { id: 'r17', studentName: '同学Q', rating: 5, content: '普拉提比想象中难,但教练教得很细,每个动作都解释清楚', date: isoDaysAgo(6) },
    ],
    successCases: ['帮多位久坐同学改善圆肩驼背问题', '一位同学3个月体态评估从C级提升到A级'],
  },
  {
    id: 'c9',
    userId: 'u7',
    name: '孙婷婷',
    department: '管理学院',
    grade: '2023级',
    specialties: ['形体矫正', '拉伸放松'],
    styleDesc: '帮助女生建立正确训练习惯,注重形体和体态改善',
    isBeginnerFriendly: true,
    isFemaleFriendly: true,
    totalSessions: 0,
    totalStudents: 0,
    certStatus: 'pending',
    certAppliedAt: isoDaysAgo(2),
    venues: ['v2'],
    createdAt: isoDaysAgo(100),
  },
  {
    id: 'c10',
    userId: 'u8',
    name: '周文博',
    department: '数学科学学院',
    grade: '2021级',
    specialties: ['力量训练', '营养指导'],
    styleDesc: '4年训练经验,擅长力量入门和计划制定,同时提供基础营养建议',
    isBeginnerFriendly: false,
    isFemaleFriendly: false,
    totalSessions: 0,
    totalStudents: 0,
    certStatus: 'pending',
    certAppliedAt: isoDaysAgo(1),
    venues: ['v1', 'v3'],
    createdAt: isoDaysAgo(90),
  },
];

// ========== 教练可用时段(90+ 条,日期动态) ==========
// 覆盖8位认证教练、4个可预约场馆、未来14天、早中晚多时段
export const mockSlots: CoachSlot[] = [
  // ===== 教练c1 张明 (南区v1 + 北区v2 + 江湾v4, 力量训练+新手友好) =====
  { id: 's1', coachId: 'c1', venueId: 'v1', date: day(0), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's2', coachId: 'c1', venueId: 'v1', date: day(0), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's3', coachId: 'c1', venueId: 'v1', date: day(0), startTime: '19:00', endTime: '20:00', isAvailable: false },
  { id: 's4', coachId: 'c1', venueId: 'v1', date: day(1), startTime: '09:00', endTime: '10:00', isAvailable: true },
  { id: 's5', coachId: 'c1', venueId: 'v1', date: day(1), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's6', coachId: 'c1', venueId: 'v2', date: day(2), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's7', coachId: 'c1', venueId: 'v2', date: day(2), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's8', coachId: 'c1', venueId: 'v1', date: day(3), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's9', coachId: 'c1', venueId: 'v1', date: day(4), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's10', coachId: 'c1', venueId: 'v2', date: day(5), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's11', coachId: 'c1', venueId: 'v1', date: day(6), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's101', coachId: 'c1', venueId: 'v1', date: day(7), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's102', coachId: 'c1', venueId: 'v2', date: day(9), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's103', coachId: 'c1', venueId: 'v1', date: day(10), startTime: '19:00', endTime: '20:00', isAvailable: false },
  { id: 's104', coachId: 'c1', venueId: 'v4', date: day(1), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's105', coachId: 'c1', venueId: 'v4', date: day(3), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's106', coachId: 'c1', venueId: 'v4', date: day(6), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's107', coachId: 'c1', venueId: 'v4', date: day(10), startTime: '15:00', endTime: '16:00', isAvailable: true },

  // ===== 教练c2 李晓燕 (南区v1 + 北区v2, 女生友好+有氧减脂) =====
  { id: 's12', coachId: 'c2', venueId: 'v2', date: day(0), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's13', coachId: 'c2', venueId: 'v2', date: day(0), startTime: '16:00', endTime: '17:00', isAvailable: false },
  { id: 's14', coachId: 'c2', venueId: 'v1', date: day(1), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's15', coachId: 'c2', venueId: 'v1', date: day(1), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's16', coachId: 'c2', venueId: 'v2', date: day(3), startTime: '09:00', endTime: '10:00', isAvailable: true },
  { id: 's17', coachId: 'c2', venueId: 'v2', date: day(3), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's18', coachId: 'c2', venueId: 'v1', date: day(4), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's19', coachId: 'c2', venueId: 'v1', date: day(5), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's20', coachId: 'c2', venueId: 'v2', date: day(6), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's108', coachId: 'c2', venueId: 'v1', date: day(7), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's109', coachId: 'c2', venueId: 'v2', date: day(8), startTime: '14:00', endTime: '15:00', isAvailable: false },
  { id: 's110', coachId: 'c2', venueId: 'v1', date: day(10), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's111', coachId: 'c2', venueId: 'v2', date: day(12), startTime: '19:00', endTime: '20:00', isAvailable: true },

  // ===== 教练c3 王浩 (南区v1 + 工会v3 + 江湾v4, 力量训练+增肌) =====
  { id: 's21', coachId: 'c3', venueId: 'v1', date: day(0), startTime: '18:00', endTime: '19:00', isAvailable: false },
  { id: 's22', coachId: 'c3', venueId: 'v3', date: day(1), startTime: '12:00', endTime: '13:00', isAvailable: true },
  { id: 's23', coachId: 'c3', venueId: 'v3', date: day(1), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's24', coachId: 'c3', venueId: 'v1', date: day(2), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's25', coachId: 'c3', venueId: 'v3', date: day(3), startTime: '12:00', endTime: '13:00', isAvailable: true },
  { id: 's26', coachId: 'c3', venueId: 'v1', date: day(4), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's27', coachId: 'c3', venueId: 'v3', date: day(5), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's28', coachId: 'c3', venueId: 'v1', date: day(6), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's112', coachId: 'c3', venueId: 'v1', date: day(7), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's113', coachId: 'c3', venueId: 'v3', date: day(8), startTime: '12:00', endTime: '13:00', isAvailable: false },
  { id: 's114', coachId: 'c3', venueId: 'v1', date: day(9), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's115', coachId: 'c3', venueId: 'v3', date: day(11), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's116', coachId: 'c3', venueId: 'v4', date: day(0), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's117', coachId: 'c3', venueId: 'v4', date: day(4), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's118', coachId: 'c3', venueId: 'v4', date: day(6), startTime: '16:00', endTime: '17:00', isAvailable: false },
  { id: 's119', coachId: 'c3', venueId: 'v4', date: day(11), startTime: '10:00', endTime: '11:00', isAvailable: true },

  // ===== 教练c4 陈思怡 (北区v2, 有氧拉伸+女生友好) =====
  { id: 's29', coachId: 'c4', venueId: 'v2', date: day(1), startTime: '08:00', endTime: '09:00', isAvailable: true },
  { id: 's30', coachId: 'c4', venueId: 'v2', date: day(2), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's31', coachId: 'c4', venueId: 'v2', date: day(4), startTime: '09:00', endTime: '10:00', isAvailable: true },
  { id: 's32', coachId: 'c4', venueId: 'v2', date: day(5), startTime: '15:00', endTime: '16:00', isAvailable: false },
  { id: 's33', coachId: 'c4', venueId: 'v2', date: day(6), startTime: '09:00', endTime: '10:00', isAvailable: true },
  { id: 's120', coachId: 'c4', venueId: 'v2', date: day(7), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's121', coachId: 'c4', venueId: 'v2', date: day(9), startTime: '08:00', endTime: '09:00', isAvailable: true },
  { id: 's122', coachId: 'c4', venueId: 'v2', date: day(10), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's123', coachId: 'c4', venueId: 'v2', date: day(12), startTime: '09:00', endTime: '10:00', isAvailable: false },
  { id: 's124', coachId: 'c4', venueId: 'v2', date: day(13), startTime: '16:00', endTime: '17:00', isAvailable: true },

  // ===== 教练c5 赵宇航 (南区v1 + 工会v3, 力量训练+新手友好) =====
  { id: 's34', coachId: 'c5', venueId: 'v1', date: day(1), startTime: '10:00', endTime: '11:00', isAvailable: false },
  { id: 's35', coachId: 'c5', venueId: 'v3', date: day(2), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's36', coachId: 'c5', venueId: 'v1', date: day(3), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's37', coachId: 'c5', venueId: 'v3', date: day(4), startTime: '12:00', endTime: '13:00', isAvailable: true },
  { id: 's38', coachId: 'c5', venueId: 'v1', date: day(5), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's39', coachId: 'c5', venueId: 'v1', date: day(6), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's125', coachId: 'c5', venueId: 'v3', date: day(7), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's126', coachId: 'c5', venueId: 'v1', date: day(8), startTime: '10:00', endTime: '11:00', isAvailable: false },
  { id: 's127', coachId: 'c5', venueId: 'v1', date: day(10), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's128', coachId: 'c5', venueId: 'v3', date: day(12), startTime: '12:00', endTime: '13:00', isAvailable: true },

  // ===== 教练c6 孙雨萱 (南区v1 + 北区v2, 瑜伽+冥想+女生友好) =====
  { id: 's40', coachId: 'c6', venueId: 'v1', date: day(0), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's129', coachId: 'c6', venueId: 'v2', date: day(1), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's130', coachId: 'c6', venueId: 'v2', date: day(1), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's131', coachId: 'c6', venueId: 'v1', date: day(2), startTime: '14:00', endTime: '15:00', isAvailable: false },
  { id: 's132', coachId: 'c6', venueId: 'v1', date: day(3), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's133', coachId: 'c6', venueId: 'v2', date: day(4), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's134', coachId: 'c6', venueId: 'v1', date: day(5), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's135', coachId: 'c6', venueId: 'v2', date: day(6), startTime: '10:00', endTime: '11:00', isAvailable: false },
  { id: 's136', coachId: 'c6', venueId: 'v1', date: day(7), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's137', coachId: 'c6', venueId: 'v2', date: day(9), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's138', coachId: 'c6', venueId: 'v1', date: day(11), startTime: '10:00', endTime: '11:00', isAvailable: true },

  // ===== 教练c7 林晨宇 (南区v1 + 工会v3, HIIT+功能性训练) =====
  { id: 's139', coachId: 'c7', venueId: 'v1', date: day(0), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's140', coachId: 'c7', venueId: 'v3', date: day(1), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's141', coachId: 'c7', venueId: 'v1', date: day(2), startTime: '10:00', endTime: '11:00', isAvailable: false },
  { id: 's142', coachId: 'c7', venueId: 'v1', date: day(3), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's143', coachId: 'c7', venueId: 'v3', date: day(4), startTime: '18:00', endTime: '19:00', isAvailable: true },
  { id: 's144', coachId: 'c7', venueId: 'v1', date: day(5), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's145', coachId: 'c7', venueId: 'v1', date: day(6), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's146', coachId: 'c7', venueId: 'v3', date: day(7), startTime: '18:00', endTime: '19:00', isAvailable: false },
  { id: 's147', coachId: 'c7', venueId: 'v1', date: day(8), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's148', coachId: 'c7', venueId: 'v1', date: day(10), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's149', coachId: 'c7', venueId: 'v3', date: day(12), startTime: '18:00', endTime: '19:00', isAvailable: true },

  // ===== 教练c8 钱梦瑶 (北区v2, 普拉提+核心+体态矫正+女生友好) =====
  { id: 's150', coachId: 'c8', venueId: 'v2', date: day(1), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's151', coachId: 'c8', venueId: 'v2', date: day(2), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's152', coachId: 'c8', venueId: 'v2', date: day(3), startTime: '16:00', endTime: '17:00', isAvailable: false },
  { id: 's153', coachId: 'c8', venueId: 'v2', date: day(4), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's154', coachId: 'c8', venueId: 'v2', date: day(5), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's155', coachId: 'c8', venueId: 'v2', date: day(6), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's156', coachId: 'c8', venueId: 'v2', date: day(8), startTime: '16:00', endTime: '17:00', isAvailable: true },
  { id: 's157', coachId: 'c8', venueId: 'v2', date: day(9), startTime: '10:00', endTime: '11:00', isAvailable: false },
  { id: 's158', coachId: 'c8', venueId: 'v2', date: day(11), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's159', coachId: 'c8', venueId: 'v2', date: day(13), startTime: '10:00', endTime: '11:00', isAvailable: true },

  // ===== 教练c6 孙雨萱 江湾v4 时段 =====
  { id: 's41', coachId: 'c6', venueId: 'v4', date: day(2), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's42', coachId: 'c6', venueId: 'v4', date: day(2), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's43', coachId: 'c6', venueId: 'v1', date: day(4), startTime: '19:00', endTime: '20:00', isAvailable: false },
  { id: 's44', coachId: 'c6', venueId: 'v4', date: day(5), startTime: '09:00', endTime: '10:00', isAvailable: true },
  { id: 's45', coachId: 'c6', venueId: 'v4', date: day(5), startTime: '15:00', endTime: '16:00', isAvailable: true },
  { id: 's46', coachId: 'c6', venueId: 'v1', date: day(6), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's160', coachId: 'c6', venueId: 'v4', date: day(9), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's161', coachId: 'c6', venueId: 'v4', date: day(12), startTime: '14:00', endTime: '15:00', isAvailable: false },

  // ===== 教练c2 李晓燕 江湾v4 时段 =====
  { id: 's162', coachId: 'c2', venueId: 'v4', date: day(1), startTime: '14:00', endTime: '15:00', isAvailable: true },
  { id: 's163', coachId: 'c2', venueId: 'v4', date: day(5), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's164', coachId: 'c2', venueId: 'v4', date: day(8), startTime: '15:00', endTime: '16:00', isAvailable: false },
  { id: 's165', coachId: 'c2', venueId: 'v4', date: day(11), startTime: '10:00', endTime: '11:00', isAvailable: true },

  // ===== 教练c7 林晨宇 江湾v4 时段 =====
  { id: 's166', coachId: 'c7', venueId: 'v4', date: day(3), startTime: '19:00', endTime: '20:00', isAvailable: true },
  { id: 's167', coachId: 'c7', venueId: 'v4', date: day(7), startTime: '10:00', endTime: '11:00', isAvailable: true },
  { id: 's168', coachId: 'c7', venueId: 'v4', date: day(10), startTime: '19:00', endTime: '20:00', isAvailable: false },
];

// ========== 预约记录(6 条,覆盖全部状态,日期动态) ==========
// a1 pending(本周,占 u1 额度), a2 approved(本周,占 u1 额度)
// a3 completed(上周,u7), a4 cancelled(上周,u1,记违约), a5 pending(本周,u8), a6 no_show(上上周,u9)
export const mockAppointments: Appointment[] = [
  {
    id: 'a1',
    studentId: 'u1',
    coachId: 'c1',
    venueId: 'v1',
    date: day(1),
    startTime: '14:00',
    endTime: '15:00',
    status: 'pending',
    trainingNote: '零基础,想学基本器械使用方法',
    createdAt: isoDaysAgo(0),
  },
  {
    id: 'a2',
    studentId: 'u1',
    coachId: 'c2',
    venueId: 'v2',
    date: day(2),
    startTime: '14:00',
    endTime: '15:00',
    status: 'approved',
    trainingNote: '想减脂,有氧训练为主',
    createdAt: isoDaysAgo(2),
  },
  {
    id: 'a3',
    studentId: 'u7',
    coachId: 'c3',
    venueId: 'v1',
    date: isoDaysAgo(7).slice(0, 10),
    startTime: '16:00',
    endTime: '17:00',
    status: 'completed',
    trainingNote: '力量训练入门',
    createdAt: isoDaysAgo(9),
  },
  {
    id: 'a4',
    studentId: 'u1',
    coachId: 'c5',
    venueId: 'v3',
    date: isoDaysAgo(5).slice(0, 10),
    startTime: '14:00',
    endTime: '15:00',
    status: 'cancelled',
    cancelReason: '教练未及时审核,系统自动取消',
    cancelledBy: 'system',
    cancelledAt: isoDaysAgo(4),
    createdAt: isoDaysAgo(6),
  },
  {
    id: 'a5',
    studentId: 'u8',
    coachId: 'c1',
    venueId: 'v1',
    date: day(2),
    startTime: '10:00',
    endTime: '11:00',
    status: 'pending',
    trainingNote: '想学卧推和深蹲',
    createdAt: isoDaysAgo(1),
  },
  {
    id: 'a6',
    studentId: 'u9',
    coachId: 'c4',
    venueId: 'v2',
    date: isoDaysAgo(10).slice(0, 10),
    startTime: '08:00',
    endTime: '09:00',
    status: 'no_show',
    trainingNote: '',
    createdAt: isoDaysAgo(12),
  },
];

// ========== 公告(3 条) ==========
export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann1',
    title: '【重要】2025年秋季学期带练预约已开放',
    content:
      '本学期邯郸南区、北区、五六教工会三场馆带练预约现已开放。欢迎新老社员预约,每周每人最多预约3次。请仔细阅读预约规则后再提交。',
    isPinned: true,
    status: 'published',
    publishedAt: isoDaysAgo(3),
  },
  {
    id: 'ann2',
    title: '暑期南区场馆开放时间调整通知',
    content: '7月1日至8月31日,邯郸南区健身房开放时间调整为08:00-20:00,请合理安排训练时间。',
    isPinned: false,
    status: 'published',
    publishedAt: isoDaysAgo(6),
  },
  {
    id: 'ann3',
    title: '新增3位认证教练,欢迎预约',
    content: '恭喜赵宇航、孙婷婷、周文博三位社员通过教练认证审核,现已开放预约时段。',
    isPinned: false,
    status: 'published',
    publishedAt: isoDaysAgo(9),
  },
];

// ========== 违约记录(2 条) ==========
export const mockViolations: ViolationRecord[] = [
  {
    id: 'vr1',
    userId: 'u9',
    appointmentId: 'a6',
    violationType: 'no_show',
    description: '2025-06-25 预约未到场(教练:陈思怡,邯郸北区 08:00-09:00)',
    createdAt: isoDaysAgo(10),
  },
  {
    id: 'vr2',
    userId: 'u1',
    appointmentId: 'a4',
    violationType: 'late_cancel',
    description: '2025-06-28 预约在开课前 12 小时内取消(教练:赵宇航,五六教工会 14:00-15:00)',
    createdAt: isoDaysAgo(5),
  },
];

// ========== 一键登录账号清单(登录页展示) ==========
export const QUICK_LOGIN_ACCOUNTS = [
  { studentId: '22300110001', password: 'password123', label: '学员·刘小明', desc: '普通社员,已预约2次' },
  { studentId: '22300150002', password: 'password123', label: '教练·张明', desc: '认证教练,力量训练专家' },
  { studentId: '22300060009', password: 'password123', label: '学员·吴雨桐', desc: '被禁约(测试禁约提示)' },
  { studentId: '00000000000', password: 'admin123', label: '管理员', desc: '后台全部权限' },
  { studentId: '22300210019', password: 'password123', label: '女生学员·陈雅婷', desc: '常预约女生教练,10次训练' },
  { studentId: '22300100008', password: 'password123', label: '新手学员·林浩然', desc: '零基础,0次训练' },
  { studentId: '22300250015', password: 'password123', label: '江湾学员·许佳音', desc: '江湾校区,常去江湾健身房' },
  { studentId: '22300090018', password: 'password123', label: '健身达人·梁文博', desc: '15次训练,连续打卡7天' },
  { studentId: '22300180011', password: 'password123', label: '瑜伽爱好者·黄丽雯', desc: '主要预约瑜伽/普拉提' },
  { studentId: '22300280017', password: 'password123', label: '减脂学员·钱梦瑶', desc: '正在减脂,以有氧训练为主' },
];
